### DISCUSSION TITLE
低代码简易博客，从Github仓库获取

### DISCUSSION THREAD

**Discussion by ChenYFan** [ChenYFan/ClientWorker#8] [Awesome Example]
Demo: <https://129e0873.solopage.pages.dev/>

`config.yaml` :
```yaml
name: simpleBlog
catch_rules: 
    - rule: ^https\:\/\/rmt\.dogedoge\.com
      transform_rules: 
        - search: _
          replace: https://rmt.ladydaily.com

    - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|unpkg\.com|npm\.elemecdn\.com)
      transform_rules:
      - search: _
        replace:
          - _
          - https://unpkg.com
          - https://fastly.jsdelivr.net/npm
          - https://unpkg.zhimg.com 
          - https://npm.elemecdn.com 
          - https://code.bdstatic.com/npm 
          - https://npm.sourcegcdn.com 
          - https://cdn.bilicdn.tk/npm 
        action: fetch
        fetch:
          preflight: false
          engine: parallel

    - rule: _ 
      transform_rules: 
            - search: \#.*
              searchin: url 
              replace: ''
            - search: \?.* 
              replace: '' 
            - search: ([^\/.]+)\/index(|\.html)$ 
              action: redirect
              redirect: 
                to: $1/
            - search: \/$
              action: script
              script:
                name: list_post
                skip: true
            - search: \.md$
              action: script
              script:
                name: show_post
                skip: true
```

`cw.js` :
```javascript
importScripts('https://unpkg.com/clientworker@2.7.2-beta-2/dist/cw.js')
importScripts('https://npm.sourcegcdn.com/marked@4.0.18/marked.min.js')

const list_post = async (args) =>{
    const urlObj = new URL(args.request.url)
    const path = urlObj.pathname
    const githubapiend = 'https://api.github.com/repos/ChenYFan/blog/contents/source/_posts' + path
    return fetch(githubapiend).then(res => res.json()).then(res => {
        const posts = res.filter(item => item.name.endsWith('.md')).map(item => {
            return {
                name: item.name,
                url: item.path
            }
        }).sort((a, b) => {
            return b.name.split('-')[0] - a.name.split('-')[0]
        }).map(item => {
            return {
                name: item.name,
                url: item.url.replace('source/_posts','')
            }
        })
        let html = '<h1>CyanFalseの博客</h1></br>'
        posts.forEach(item => {
            html += `<a href="${item.url}">${item.name.replace(/\.md$/g,'')}</a><br>`
        })
        return {
            fetched: true,
            response: new Response(html,{
                headers:{
                    'Content-Type': 'text/html;charset=utf-8'
                }
            })
        }
    })
}

const show_post = async (args) =>{
    const urlObj = new URL(args.request.url)
    const path = urlObj.pathname
    const githubdownloadend = 'https://raw.githubusercontent.com/ChenYFan/blog/master/source/_posts' + path
    return fetch(githubdownloadend).then(res => res.text()).then(res => {
        return {
            fetched: true,
            response: new Response('<a href="/">👈返回主页</a></br>'+marked.parse(res),{
                headers:{
                    'Content-Type': 'text/html;charset=utf-8'
                }
            })
        }
    })
}
```
